spring:
  datasource:
    dynamic:
      primary: master # 设置默认数据源
      datasource:
        master:  # 主数据源（原来的MySQL数据源）
          url: jdbc:mysql://localhost:3306/calcite_conf?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: Qq111111
          driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: true


vatica:
  thread-pool:
    core-size: 10
    max-size: 50
    queue-capacity: 100
    thread-name-prefix: avatica-server-

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

calcite:
  datasource-file: "C:\\Users\\AH\\idea\\demo\\demo\\src\\main\\resources\\model.json"
  server:
    port: 8765
    enabled: true
    serialization: JSON

logging:
  level:
    com.zaxxer.hikari: error
    com.zaxxer.hikariConfig: error
    com.zaxxer.hikari.pool.HikariPool:
    com.zaxxer.hikari.pool.PoolBase: error