server:
  port: 8081

logging:
  level:
    org.apache.calcite.avatica: INFO
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.HikariConfig: info
    com.zaxxer.hikari.pool.HikariPool: info
    com.zaxxer.hikari.pool.PoolBase: TRACE
    com.zaxxer.hikari.connection: TRACE
    com.zaxxer.hikari.pool.ProxyConnection: TRACE
    com.zaxxer.hikari.pool.HikariProxyConnection: TRACE
    com.example.client.mapper: DEBUG
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    com.example.client.monitor: INFO


spring:
  datasource:
    url: jdbc:ah:url=http://localhost:8765
    driver-class-name: com.example.client.config.MyDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 5000
      pool-name: avatica-client-pool
      register-mbeans: true
      data-source-properties:  # calcite自定义参数
        serialization: JSON
        authentication: BASIC
        username: admin
        password: admin
