server:
  port: 8081

avatica:
  client:
    url: jdbc:avatica:remote:url=http://localhost:8765
    serialization: JSON
    connect-timeout: 30000
    socket-timeout: 60000

logging:
  level:
    org.apache.calcite.avatica: INFO
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.example.client.mapper: DEBUG
    org.apache.ibatis: DEBUG
    java.sql: DEBUG


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 禁用自动提交的事务管理
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: none
      table-underline: true


spring:
  datasource:
    url: jdbc:avatica:remote:url=http://localhost:8765;serialization=JSON
    driver-class-name: org.apache.calcite.avatica.remote.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      pool-name: avatica-client-pool
      connection-test-query: SELECT 1
